// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDEFM4ALQCr6Mp8bNdZTBfKew8DaqL4fo',
    appId: '1:553398879251:web:625d4c147dc8d2a0406be6',
    messagingSenderId: '553398879251',
    projectId: 'flutter-firebase-demo-aldi',
    authDomain: 'flutter-firebase-demo-aldi.firebaseapp.com',
    storageBucket: 'flutter-firebase-demo-aldi.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZUJWjzgvs6-BRAhURKF4k2hl78_uE_gI',
    appId: '1:553398879251:android:15e4303dfe293ddc406be6',
    messagingSenderId: '553398879251',
    projectId: 'flutter-firebase-demo-aldi',
    storageBucket: 'flutter-firebase-demo-aldi.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLumB1Z5zJl1H0ya4JIyvsQxR2f2my5lY',
    appId: '1:553398879251:ios:a977536771f7b1a0406be6',
    messagingSenderId: '553398879251',
    projectId: 'flutter-firebase-demo-aldi',
    storageBucket: 'flutter-firebase-demo-aldi.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseDemo',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLumB1Z5zJl1H0ya4JIyvsQxR2f2my5lY',
    appId: '1:553398879251:ios:a977536771f7b1a0406be6',
    messagingSenderId: '553398879251',
    projectId: 'flutter-firebase-demo-aldi',
    storageBucket: 'flutter-firebase-demo-aldi.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDEFM4ALQCr6Mp8bNdZTBfKew8DaqL4fo',
    appId: '1:553398879251:web:b5f5ca2411c5a1dc406be6',
    messagingSenderId: '553398879251',
    projectId: 'flutter-firebase-demo-aldi',
    authDomain: 'flutter-firebase-demo-aldi.firebaseapp.com',
    storageBucket: 'flutter-firebase-demo-aldi.firebasestorage.app',
  );
}
